apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: hrbuddy
stringData:
  QUARKUS_REST_CLIENT_IVAN_SCRAPER_URL: "http://python-service:8000"
  QUARKUS_REST_CLIENT_ANALYZER_URL: "http://php-service:9000"
  JWT_SECRET_KEY: "1a2b3c4d5e6f7g8h9i0j1k2l3m4n5o6p7q8r9s0t"
  QUARKUS_DATASOURCE_JDBC_URL: "jdbc:mysql://root:secret@mysql:3306/quarkus_db"